// Generated by Ignite ignite.com/cli

import { StdFee } from "@cosmjs/launchpad";
import { SigningStargateClient, DeliverTxResponse } from "@cosmjs/stargate";
import { EncodeObject, GeneratedType, OfflineSigner, Registry } from "@cosmjs/proto-signing";
import { msgTypes } from './registry';
import { IgniteClient } from "../client"
import { MissingWalletError } from "../helpers"
import { Api } from "./rest";
import { MsgUpdatePost } from "./types/protoqol/protoqol/tx";
import { MsgCreatePost } from "./types/protoqol/protoqol/tx";
import { MsgDeletePost } from "./types/protoqol/protoqol/tx";
import { MsgWriteComment } from "./types/protoqol/protoqol/tx";


export { MsgUpdatePost, MsgCreatePost, MsgDeletePost, MsgWriteComment };

type sendMsgUpdatePostParams = {
  value: MsgUpdatePost,
  fee?: StdFee,
  memo?: string
};

type sendMsgCreatePostParams = {
  value: MsgCreatePost,
  fee?: StdFee,
  memo?: string
};

type sendMsgDeletePostParams = {
  value: MsgDeletePost,
  fee?: StdFee,
  memo?: string
};

type sendMsgWriteCommentParams = {
  value: MsgWriteComment,
  fee?: StdFee,
  memo?: string
};


type msgUpdatePostParams = {
  value: MsgUpdatePost,
};

type msgCreatePostParams = {
  value: MsgCreatePost,
};

type msgDeletePostParams = {
  value: MsgDeletePost,
};

type msgWriteCommentParams = {
  value: MsgWriteComment,
};


export const registry = new Registry(msgTypes);

const defaultFee = {
  amount: [],
  gas: "200000",
};

interface TxClientOptions {
  addr: string
	prefix: string
	signer?: OfflineSigner
}

export const txClient = ({ signer, prefix, addr }: TxClientOptions = { addr: "http://localhost:26657", prefix: "cosmos" }) => {

  return {
		
		async sendMsgUpdatePost({ value, fee, memo }: sendMsgUpdatePostParams): Promise<DeliverTxResponse> {
			if (!signer) {
					throw new Error('TxClient:sendMsgUpdatePost: Unable to sign Tx. Signer is not present.')
			}
			try {			
				const { address } = (await signer.getAccounts())[0]; 
				const signingClient = await SigningStargateClient.connectWithSigner(addr,signer,{registry, prefix});
				let msg = this.msgUpdatePost({ value: MsgUpdatePost.fromPartial(value) })
				return await signingClient.signAndBroadcast(address, [msg], fee ? fee : defaultFee, memo)
			} catch (e: any) {
				throw new Error('TxClient:sendMsgUpdatePost: Could not broadcast Tx: '+ e.message)
			}
		},
		
		async sendMsgCreatePost({ value, fee, memo }: sendMsgCreatePostParams): Promise<DeliverTxResponse> {
			if (!signer) {
					throw new Error('TxClient:sendMsgCreatePost: Unable to sign Tx. Signer is not present.')
			}
			try {			
				const { address } = (await signer.getAccounts())[0]; 
				const signingClient = await SigningStargateClient.connectWithSigner(addr,signer,{registry, prefix});
				let msg = this.msgCreatePost({ value: MsgCreatePost.fromPartial(value) })
				return await signingClient.signAndBroadcast(address, [msg], fee ? fee : defaultFee, memo)
			} catch (e: any) {
				throw new Error('TxClient:sendMsgCreatePost: Could not broadcast Tx: '+ e.message)
			}
		},
		
		async sendMsgDeletePost({ value, fee, memo }: sendMsgDeletePostParams): Promise<DeliverTxResponse> {
			if (!signer) {
					throw new Error('TxClient:sendMsgDeletePost: Unable to sign Tx. Signer is not present.')
			}
			try {			
				const { address } = (await signer.getAccounts())[0]; 
				const signingClient = await SigningStargateClient.connectWithSigner(addr,signer,{registry, prefix});
				let msg = this.msgDeletePost({ value: MsgDeletePost.fromPartial(value) })
				return await signingClient.signAndBroadcast(address, [msg], fee ? fee : defaultFee, memo)
			} catch (e: any) {
				throw new Error('TxClient:sendMsgDeletePost: Could not broadcast Tx: '+ e.message)
			}
		},
		
		async sendMsgWriteComment({ value, fee, memo }: sendMsgWriteCommentParams): Promise<DeliverTxResponse> {
			if (!signer) {
					throw new Error('TxClient:sendMsgWriteComment: Unable to sign Tx. Signer is not present.')
			}
			try {			
				const { address } = (await signer.getAccounts())[0]; 
				const signingClient = await SigningStargateClient.connectWithSigner(addr,signer,{registry, prefix});
				let msg = this.msgWriteComment({ value: MsgWriteComment.fromPartial(value) })
				return await signingClient.signAndBroadcast(address, [msg], fee ? fee : defaultFee, memo)
			} catch (e: any) {
				throw new Error('TxClient:sendMsgWriteComment: Could not broadcast Tx: '+ e.message)
			}
		},
		
		
		msgUpdatePost({ value }: msgUpdatePostParams): EncodeObject {
			try {
				return { typeUrl: "/protoqol.protoqol.MsgUpdatePost", value: MsgUpdatePost.fromPartial( value ) }  
			} catch (e: any) {
				throw new Error('TxClient:MsgUpdatePost: Could not create message: ' + e.message)
			}
		},
		
		msgCreatePost({ value }: msgCreatePostParams): EncodeObject {
			try {
				return { typeUrl: "/protoqol.protoqol.MsgCreatePost", value: MsgCreatePost.fromPartial( value ) }  
			} catch (e: any) {
				throw new Error('TxClient:MsgCreatePost: Could not create message: ' + e.message)
			}
		},
		
		msgDeletePost({ value }: msgDeletePostParams): EncodeObject {
			try {
				return { typeUrl: "/protoqol.protoqol.MsgDeletePost", value: MsgDeletePost.fromPartial( value ) }  
			} catch (e: any) {
				throw new Error('TxClient:MsgDeletePost: Could not create message: ' + e.message)
			}
		},
		
		msgWriteComment({ value }: msgWriteCommentParams): EncodeObject {
			try {
				return { typeUrl: "/protoqol.protoqol.MsgWriteComment", value: MsgWriteComment.fromPartial( value ) }  
			} catch (e: any) {
				throw new Error('TxClient:MsgWriteComment: Could not create message: ' + e.message)
			}
		},
		
	}
};

interface QueryClientOptions {
  addr: string
}

export const queryClient = ({ addr: addr }: QueryClientOptions = { addr: "http://localhost:1317" }) => {
  return new Api({ baseURL: addr });
};

class SDKModule {
	public query: ReturnType<typeof queryClient>;
	public tx: ReturnType<typeof txClient>;
	
	public registry: Array<[string, GeneratedType]> = [];

	constructor(client: IgniteClient) {		
	
		this.query = queryClient({ addr: client.env.apiURL });		
		this.updateTX(client);
		client.on('signer-changed',(signer) => {			
		 this.updateTX(client);
		})
	}
	updateTX(client: IgniteClient) {
    const methods = txClient({
        signer: client.signer,
        addr: client.env.rpcURL,
        prefix: client.env.prefix ?? "cosmos",
    })
	
    this.tx = methods;
    for (let m in methods) {
        this.tx[m] = methods[m].bind(this.tx);
    }
	}
};

const Module = (test: IgniteClient) => {
	return {
		module: {
			ProtoqolProtoqol: new SDKModule(test)
		},
		registry: msgTypes
  }
}
export default Module;